packages:
  - "apps/*"
  - "packages/*"
  - "services/*"
  - "infrastructure/*"
allowBuilds:
  '@clerk/shared': false
  '@prisma/engines': false
  esbuild: false
  msgpackr-extract: false
  msw: false
  prisma: false
  sharp: true
  unrs-resolver: true
