ALTER TYPE "WorkflowEventType" ADD VALUE IF NOT EXISTS 'IMAGES_UPLOADED';
ALTER TYPE "WorkflowEventType" ADD VALUE IF NOT EXISTS 'ORDER_SUBMITTED';
ALTER TYPE "WorkflowEventType" ADD VALUE IF NOT EXISTS 'EDITOR_STARTED';
ALTER TYPE "WorkflowEventType" ADD VALUE IF NOT EXISTS 'QA_ASSIGNED';
ALTER TYPE "WorkflowEventType" ADD VALUE IF NOT EXISTS 'READY_FOR_QA';
ALTER TYPE "WorkflowEventType" ADD VALUE IF NOT EXISTS 'QA_APPROVED';
ALTER TYPE "WorkflowEventType" ADD VALUE IF NOT EXISTS 'QA_REVISION_REQUESTED';
ALTER TYPE "WorkflowEventType" ADD VALUE IF NOT EXISTS 'ORDER_STATUS_CHANGED';
